import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import Navbar from './components/home/Navbar'
import Footer from './components/home/Footer'

export const metadata = {
  title: 'Grayscale Digitals',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className=''>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
